---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mcm-finance-deployable-deployment-redis
  namespace: mcm-finance-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: mcm-finance-application
    subApp: web
spec:
  template:
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: mcm-finance-busybox
      namespace: mcm-finance-app-ns
    spec:
      serviceName: "local-service"
      replicas: 3
      selector:
        matchLabels:
          app: mcm-finance-application
          subname: busybox
      template:
        metadata:
          labels:
            app: mcm-finance-application
            subname: busybox
        spec:
          containers:
          - name: test-container
            image: k8s.gcr.io/busybox
            command:
            - "/bin/sh"
            args:
            - "-c"
            - "sleep 100000"
            volumeMounts:
            - name: local-vol
              mountPath: /usr/
      volumeClaimTemplates:
      - metadata:
          name: local-vol
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "local-storage"
          resources:
            requests:
              storage: 10Gi
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: mcm-finance-deployable-storageclass-busybox
  namespace: mcm-finance-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"  
  labels:
    app: mcm-finance-application
    subApp: web
spec:
  template:
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: mcm-finance-busybox-storageclass
      labels:
        app: mcm-finance-application
        subname: busybox      
    spec:
      provisioner: kubernetes.io/no-provisioner
      volumeBindingMode: WaitForFirstConsumer
